# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdfff047588e73836a2595c2dd97a18c7ffbfe8e035457cbe16fe3d26117a5b4135e294c66cf137ed147c0aa39570f736c158711d99151b3987ad7157297b2e0

test:
  secret_key_base: 1127dc7fa920e8e0894d0187c59db7872c2b504c1be301c149f6701ee7cdb4f13c581f29887f47dfb856348f2245e528cd14fc58734a3b921eaa193b12523a02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
